services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    env_file: .env
    healthcheck:
      test: mysqladmin ping --host=localhost -p$SQL_ROOT_PASSWORD
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - wordpress
    healthcheck:
      test: 'curl -kfsSL https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

  adminer:
    build:
      context: ./bonus/adminer
    container_name: adminer
    ports:
      - "8081:80"
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vmondor/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vmondor/data/mariadb'


networks:
  inception:
    name: inception
    driver: bridge